version: '2'
services:
  mysql:
    image: mysql:latest
    ports:
      - "3308:3306"
    volumes:
      - /home/josevictor/dev/motor-cadastro-usuario/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_HOST: '%'